server:
  port: 8080
  servlet:
    context-path: /community
# 数据源基本配置
spring:
  devtools:
    restart:
      enabled: true
    livereload:
      enabled: true


  datasource:
    url: jdbc:mysql://127.0.0.1:3306/nowcoder
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: root
    type: com.alibaba.druid.pool.DruidDataSource

  mail:
    host: smtp.qq.com
    port:
    username: 2493929776@qq.com
    password: oikadxbhwbjmeadj
    properties:
      mail:
        smtp:
          ssl:
            enabled: true
    protocol: smtps


  # 指定mapper映射文件位置
mybatis:
  mapper-locations: classpath:/mapper/*.xml

  # 参数项调整
  configuration:
    map-underscore-to-camel-case: true
    use-generated-keys: true

  type-aliases-package: com.nowcoder.community.pojo


logging:
  level:
    root: info

community:
  path:
    domain: http://localhost:8080
    upload: f:/nowcoder/upload